### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by radouu1** [bditt/External-Roblox-ESP#4]
A lot of errors this is bs and not coded correctly

**Comment by RiritoNinigaya** [comment]
it is because outdated offsets, you can update offsets and try again to compile!!!

**Comment by bditt** [comment]
As stated above, you would need to update all the offset and rebuild this.
I assume a lot of the structs have changed since I've made this, as it's over 5 years old.
The code is also really poorly written and should only be used to figure out how to loop players and get instances/properties.
